@startuml
'https://plantuml.com/use-case-diagram
title   HealthCalculator use case

skinparam usecase {
BackgroundColor white
BorderColor black
BackgroundColor<< Main >> white
BorderColor black
BorderColor<< Main >> black
ArrowColor black
ActorBorderColor black
ActorFontName Courier
ActorBackgroundColor<< Human >> white
}
scale 1.3
skinparam DefaultTextAlignment left
skinparam shadowing false
skinparam packageStyle frame
hide circle

':Administrator: as Admin

User - (Verification)
(Publish) - Admin
(Verification) .. (Publish)
(Publish) .. (Create)
(Create) - Author


@enduml